Algoritmo "Exercicio6"
// Disciplina   : Linguagem e Lógica de Programação com VisualG
// Professor   : Jailson Costa
// Descrição   : Lê a base e a altura de um retângulo e fala sua área
// Autor(a)    : Guilherme Custódio Nieto
// Data atual  : 3/27/2026
Var
// Seção de Declarações das variáveis
base, altura, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite a base de um retângulo: ")
leia(base)

escreva("Digite a altura de um retângulo: ")
leia(altura)

area <- base * altura
escreva("A área do retângulo é ", area)

Fimalgoritmo