Algoritmo "Exercicio9"
// Disciplina   : Linguagem e Lógica de Programação com VisualG
// Professor   : Jailson Costa
// Descrição   : Lê o lado de um quadrado e fala sua área
// Autor(a)    : Guilherme Custódio Nieto
// Data atual  : 3/27/2026
Var
// Seção de Declarações das variáveis
ladoQuadrado, areaQuadrado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o lado de um quadrado: ")
leia(ladoQuadrado)

areaQuadrado <- ladoQuadrado * ladoQuadrado
escreval("A área do quadrado é ", areaQuadrado)


Fimalgoritmo