Algoritmo "quadrado"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Professor Obama
// Descrição   : Programa que pede o lados do quadrado e mostra sua área
// Autor(a)    : Guilherme Custódio Nieto
// Data atual  : 19/03/2026
Var
// Seção de Declarações das variáveis 
lado: real
area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Programa de cálculo de área de quadrado")
Escreva("Digite a o lado de um quadrado: ")
Leia(lado)
area <- lado * lado
Escreval("A área do quadrado é: ", area)

Fimalgoritmo