Algoritmo "salario"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Professor
// Descrição   : Um programa que lê o salário de um funcionário e mostra seu aumento
// Autor(a)    : Guilherme Custódio Nieto
// Data atual  : 19/03/2026
Var
// Seção de Declarações das variáveis
salarioAtual: real
percental: real
novoSalario: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite o seu salário atual: ")
Leia(salarioAtual)
percentual <- salarioAtual + (salarioAtual * percentual / 100)
Escreva("O novo salário é: ", salario)
Fimalgoritmo