Algoritmo "positivoOuNegativo"
// Disciplina   : Linguagem e Lógica de Programação com VIsualG e JavaScript
// Professor   : Jailson
// Descrição   : Um programa que lê um número e fala se é positivo ou negativo
// Autor(a)    : Guilherme Custódio Nieto
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Escreva um número: ")
leia(numero)
se numero < 0 entao
   escreva("O número é negativo")
senao
     escreva("O número é positivo")
fimse

Fimalgoritmo