Algoritmo "antecessor"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Professor Obama
// Descrição   : Programa que pede um número e mostra seu antecessor
// Autor(a)    : Guilherme Custódio Nieto
// Data atual  : 19/03/2026
Var
// Seção de Declarações das variáveis 
numero: inteiro
resultado: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite o número a receber o antecessor: ")
Leia(numero)
resultado <- numero - 1
Escreval("O antecessor de ", numero, " é ", resultado)

Fimalgoritmo