Algoritmo "multiplicacao"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Professor Obama
// Descrição   : Lê dois números, realiza sua múltiplicação e apresenta na tela
// Autor(a)    : Guilherme Custódio Nieto
// Data atual  : 19/03/2026
Var
// Seção de Declarações das variáveis 
numero1: inteiro
numero2: inteiro
resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Escreva o primeiro número do sistema: ")
Leia(numero1)
Escreva("Escreva o segundo número do sistema: ")
Leia(numero2)
resultado <- numero1 * numero2
Escreva("O resultado de ", numero1, " vezes ", numero2, " é ", resultado)
Fimalgoritmo