Algoritmo "nome"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Professor Obama
// Descrição   : Programa que pede um número e mostra seu sucessor
// Autor(a)    : Guilherme Custódio Nieto
// Data atual  : 19/03/2026
Var
// Seção de Declarações das variáveis 
nome: caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite o seu nome: ")
Leia(nome)
Escreval("Seu nome é: ", nome)

Fimalgoritmo