Algoritmo "semnome"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson coxinha
// Descrição   : Algoritmo onde é usado somente a subtração
// Autor(a)    : Guilherme Custódio
// Data atual  : 19/03/2026
Var
// Seção de Declarações das variáveis 
numero1: inteiro
numero2: inteiro
resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite o primeiro número a ser subtraído: ")
Leia(numero1)
Escreva("Digite o segundo número da subtração: ")
Leia(numero2)
resultado <- numero1 - numero2
Escreval("O resultado da subtração é: ", resultado)

Fimalgoritmo