Algoritmo "Exercicio8"
// Disciplina   : Linguagem e Lógica de Programação com VisualG
// Professor   : Jailson Costa
// Descrição   : Lê medidas em metros e converte para centimetros
// Autor(a)    : Guilherme Custódio Nieto
// Data atual  : 3/27/2026
Var
// Seção de Declarações das variáveis
medidaEmMetros, medidaEmCentimetros: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite a medida em metros: ")
leia(medidaEmMetros)

medidaEmCentimetros <- medidaEmMetros * 100

escreval("A medida ", medidaEmMetros, "m em centímetros fica: ", medidaEmCentimetros, "cm")


Fimalgoritmo