Algoritmo "Exercicio17"
// Disciplina   : Linguagem e Lógica de Programação com VisualG
// Professor   : Jailson Costa
// Descrição   : programa que recebe o raio do círculo e calcula sua área
// Autor(a)    : Guilherme Custódio Nieto
// Data atual  : 3/27/2026
Var
   // Seção de Declarações das variáveis
raioCirculo, areaCirculo: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Escreva o raio do círculo: ")
leia(raioCirculo)

areaCirculo <- 3.1415 * (raioCirculo * raioCirculo)
escreva("A área do círculo é ", areaCirculo)
Fimalgoritmo