Algoritmo "ifEElse"
// Disciplina   : Lógica de Programação com VisualG e JavaScript
// Professor   : Professor Obama
// Descrição   : Solicita um número e fala se é maior ou menor que 10
// Autor(a)    : Guilherme Custódio Nieto
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o número: ")
   leia(numero)
   se numero < 10 entao
      escreva("Número é menor que 10")
   senao
        escreva("Número é igual ou maior que 10")
   fimse

Fimalgoritmo